# Generated by Django 4.1.3 on 2022-11-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoryName',
        ),
    ]
